# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3eeed27e6af27bd39800395a05bf1cb2b92b5f47367bc84a1067304bd023a6e361080c9c4af5c174d43cc0fb8be19f7bbc152106fe809b7d30d9d44c35d0963

test:
  secret_key_base: 8261dc3d218370cc387b4e771a018f85630e25832657adc35fe727acfb8b67fd45fd7f1ba815e7d8433f5d14538549f58c3212eeda27d3ea92a44e1ee99dd928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
